## YAML Template.
---
## Redireccionamiento de las Ruta por Defecto | Modulo Inicial
app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

## Redireccionamiento de las Ruta por Defecto | Modulo Usuarios
app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Documentos
app_documento:
    resource: "@AppBundle/Resources/config/routing/documentos.yml"
    prefix: /documentos
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Correspondencia
app_correspondencia:
    resource: "@AppBundle/Resources/config/routing/correspondencia.yml"
    prefix: /correspondencia
    
## Redireccionamiento de las Ruta por Defecto | Modulo de ListasComunes
app_listas:
    resource: "@AppBundle/Resources/config/routing/listascomunes.yml"
    prefix: /listas
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Comunes
app_comunes:
    resource: "@AppBundle/Resources/config/routing/comunes.yml"
    prefix: /comunes
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Seguimiento
app_seguimiento:
    resource: "@AppBundle/Resources/config/routing/seguimiento.yml"
    prefix: /seguimiento