## YAML Template.
---
## Redireccionamiento de las Ruta por Defecto | Modulo Inicial
app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

## Redireccionamiento de las Ruta por Defecto | Modulo Usuarios
app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Documentos
app_documento:
    resource: "@AppBundle/Resources/config/routing/documentos.yml"
    prefix: /documentos
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Correspondencia
app_correspondencia:
    resource: "@AppBundle/Resources/config/routing/correspondencia.yml"
    prefix: /correspondencia
    
## Redireccionamiento de las Ruta por Defecto | Modulo de ListasComunes
app_listas:
    resource: "@AppBundle/Resources/config/routing/listascomunes.yml"
    prefix: /listas
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Comunes
app_comunes:
    resource: "@AppBundle/Resources/config/routing/comunes.yml"
    prefix: /comunes
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Seguimiento
app_seguimiento:
    resource: "@AppBundle/Resources/config/routing/seguimiento.yml"
    prefix: /seguimiento
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Consultas
app_consultas:
    resource: "@AppBundle/Resources/config/routing/consultas.yml"
    prefix: /consultas
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Contactos
app_contactos:
    resource: "@AppBundle/Resources/config/routing/contactos.yml"
    prefix: /contactos
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Reportes
app_reportes:
    resource: "@AppBundle/Resources/config/routing/reportes.yml"
    prefix: /reportes
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Mantenimientos
app_mantenimientos:
    resource: "@AppBundle/Resources/config/routing/mantenimientos.yml"
    prefix: /mantenimientos
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Vinculacion
app_vinculacionComunicacion:
    resource: "@AppBundle/Resources/config/routing/vinculacion.yml"
    prefix: /vinculacionComunicacion
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Charts
app_charts:
    resource: "@AppBundle/Resources/config/routing/charts.yml"
    prefix: /charts
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Unidad de Correspondencia
app_unidadCorrespondencia:
    resource: "@AppBundle/Resources/config/routing/unidad-correspondencia.yml"
    prefix: /unidad-correspondencia

## Redireccionamiento de las Ruta por Defecto | Modulo de Unidad de Correspondencia
app_documentoUnidadCorrespondencia:
    resource: "@AppBundle/Resources/config/routing/documentos-unidad-correspondencia.yml"
    prefix: /documentos-unidad-correspondencia
    
## Redireccionamiento de las Ruta por Defecto | Modulo de Comunes
app_comunesUnidadCorrespondencia:
    resource: "@AppBundle/Resources/config/routing/comunes-unidad-correspondencia.yml"
    prefix: /comunes-unidad-correspondencia