BackendBundle\Entity\TblCorrespondenciaEnc:
    type: entity
    table: tbl_correspondencia_enc
    indexes:
        fki_enc_estado:
            columns:
                - id_estado
        fki_enc_user:
            columns:
                - id_usuario
        fki_enc_inst:
            columns:
                - id_institucion
        tbl_correspondencia_enc_cod_correspondencia_enc_idx:
            columns:
                - cod_correspondencia_enc
    uniqueConstraints:
        tbl_correspondencia_enc_cod_correspondencia_enc_key:
            columns:
                - cod_correspondencia_enc
    id:
        idCorrespondenciaEnc:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_correspondencia_enc
            generator:
                strategy: SEQUENCE
    fields:
        codCorrespondenciaEnc:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: cod_correspondencia_enc
        descCorrespondenciaEnc:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: desc_correspondencia_enc
        fechaIngreso:
            type: date
            nullable: true
            column: fecha_ingreso
        fechaMaxEntrega:
            type: date
            nullable: true
            column: fecha_max_entrega
        codDireccionSreci:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: cod_direccion_sreci
    manyToOne:
        idEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idInstitucion:
            targetEntity: TblInstituciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_institucion:
                    referencedColumnName: id_institucion
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
