BackendBundle\Entity\TblContactos:
    type: entity
    table: tbl_contactos
    indexes:
        fki_contact_user_modif:
            columns:
                - id_usuario_modifica
        fki_func_contacto:
            columns:
                - id_funcionario
        tbl_contactos_cod_contacto_idx:
            columns:
                - cod_contacto
        fki_institucion_contacto:
            columns:
                - id_institucion
    id:
        idContacto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_contacto
            generator:
                strategy: SEQUENCE
    fields:
        codContacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cod_contacto
        nombre1Contacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: nombre1_contacto
        nombre2Contacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: nombre2_contacto
        apellido1Contacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: apellido1_contacto
        apellido2Contacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: apellido2_contacto
        telefono1Contacto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: telefono1_contacto
        telefono2Contacto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: telefono2_contacto
        celular1Contacto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: celular1_contacto
        celular2Contacto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: celular2_contacto
        email1Contacto:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: email1_contacto
        email2Contacto:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: email2_contacto
        fotoContacto:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: foto_contacto
        perfilContacto:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: perfil_contacto
        cargoFuncional:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: cargo_funcional
        trato:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        habilitado:
            type: boolean
            nullable: true
            options:
                default: true
        tipoContacto:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: tipo_contacto
    manyToOne:
        idUsuarioModifica:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario_modifica:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idFuncionario:
            targetEntity: TblFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_funcionario:
                    referencedColumnName: id_funcionario
            orphanRemoval: false
        idInstitucion:
            targetEntity: TblInstituciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_institucion:
                    referencedColumnName: id_institucion
            orphanRemoval: false
    lifecycleCallbacks: {  }
