BackendBundle\Entity\TblCorrespondenciaDet:
    type: entity
    table: tbl_correspondencia_det
    indexes:
        fki_det_enc:
            columns:
                - id_correspondencia_enc
        cod_oficio_respuesta:
            columns:
                - cod_oficio_respuesta
        fki_fk-det_estado:
            columns:
                - id_estado
        fki_func_det_asignado:
            columns:
                - id_funcionario_asignado
        tbl_correspondencia_det_cod_correspondencia_det_idx:
            columns:
                - cod_correspondencia_det
        fki_det_user:
            columns:
                - id_usuario
    id:
        idCorrespondenciaDet:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_correspondencia_det
            generator:
                strategy: SEQUENCE
    fields:
        codCorrespondenciaDet:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: cod_correspondencia_det
        descCorrespondenciaDet:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
            column: desc_correspondencia_det
        actividadRealizar:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: actividad_realizar
        fechaIngreso:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_ingreso
        fechaSalida:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_salida
        codReferenciaSreci:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cod_referencia_sreci
        codOficioRespuesta:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: cod_oficio_respuesta
        temaComunicacion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: tema_comunicacion
        instrucciones:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
    manyToOne:
        idEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idCorrespondenciaEnc:
            targetEntity: TblCorrespondenciaEnc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_correspondencia_enc:
                    referencedColumnName: id_correspondencia_enc
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idFuncionarioAsignado:
            targetEntity: TblFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_funcionario_asignado:
                    referencedColumnName: id_funcionario
            orphanRemoval: false
    lifecycleCallbacks: {  }
