BackendBundle\Entity\TblCorrespondenciaSalida:
    type: entity
    table: tbl_correspondencia_salida
    indexes:
        fki_estado_corr_salida:
            columns:
                - id_estado
        fki_user_corr_salida:
            columns:
                - id_usuario
        fki_correspondencia_salida_doc:
            columns:
                - id_tipo_documento
        IDX_5270D6E8FBD636DF:
            columns:
                - id_depto_funcional
        IDX_5270D6E8D9471F32:
            columns:
                - id_direccion_sreci
        IDX_5270D6E8B3C72BF6:
            columns:
                - id_funcionario_asignado
        IDX_5270D6E8C2A18A3F:
            columns:
                - id_funcionario_repartidor
        IDX_5270D6E8EF433A34:
            columns:
                - id_institucion
    id:
        idCorrespondenciaSalida:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_correspondencia_salida
            generator:
                strategy: SEQUENCE
    fields:
        codCorrespondenciaSalida:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: cod_correspondencia_salida
        nombreDestinatario:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: nombre_destinatario
        fechaRecepcion:
            type: date
            nullable: true
            column: fecha_recepcion
        horaRecepcion:
            type: time
            nullable: true
            column: hora_recepcion
        fechaEntrega:
            type: date
            nullable: true
            column: fecha_entrega
        horaEntrega:
            type: time
            nullable: true
            column: hora_entrega
        acuseDeEntrega:
            type: boolean
            nullable: true
            options:
                default: false
            column: acuse_de_entrega
    manyToOne:
        idTipoDocumento:
            targetEntity: TblTipoDocumento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_documento:
                    referencedColumnName: id_tipo_documento
            orphanRemoval: false
        idDeptoFuncional:
            targetEntity: TblDepartamentosFuncionales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_depto_funcional:
                    referencedColumnName: id_depto_funcional
            orphanRemoval: false
        idDireccionSreci:
            targetEntity: TblDireccionesSreci
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_direccion_sreci:
                    referencedColumnName: id_direccion_sreci
            orphanRemoval: false
        idEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idFuncionarioAsignado:
            targetEntity: TblFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_funcionario_asignado:
                    referencedColumnName: id_funcionario
            orphanRemoval: false
        idFuncionarioRepartidor:
            targetEntity: TblFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_funcionario_repartidor:
                    referencedColumnName: id_funcionario
            orphanRemoval: false
        idInstitucion:
            targetEntity: TblInstituciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_institucion:
                    referencedColumnName: id_institucion
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
