BackendBundle\Entity\TblCorrespondenciaEnc:
    type: entity
    table: tbl_correspondencia_enc
    indexes:
        fki_comu_docu:
            columns:
                - id_tipo_documento
        fki_enc_direccion:
            columns:
                - id_direccion_sreci
        fki_enc_user:
            columns:
                - id_usuario
        fki_corr_depto:
            columns:
                - id_depto_funcional
        fki_funcionario_asig:
            columns:
                - id_funcionario_asignado
        fki_enc_estado:
            columns:
                - id_estado
        fki_enc_inst:
            columns:
                - id_institucion
        fki_tipo_com:
            columns:
                - id_tipo_comunicacion
        tbl_correspondencia_enc_cod_correspondencia_enc_idx:
            columns:
                - cod_correspondencia_enc
    uniqueConstraints:
        tbl_correspondencia_enc_cod_correspondencia_enc_key:
            columns:
                - cod_correspondencia_enc
    id:
        idCorrespondenciaEnc:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_correspondencia_enc
            generator:
                strategy: SEQUENCE
    fields:
        codCorrespondenciaEnc:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: cod_correspondencia_enc
        descCorrespondenciaEnc:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
            column: desc_correspondencia_enc
        fechaIngreso:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_ingreso
        fechaMaxEntrega:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_max_entrega
        fechaModificacion:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_modificacion
        codReferenciaSreci:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cod_referencia_sreci
        temaComunicacion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: tema_comunicacion
        idDeptoAcomp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_depto_acomp
        fechaFinalizacion:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_finalizacion
        observaciones:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
    manyToOne:
        idTipoDocumento:
            targetEntity: TblTipoDocumento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_documento:
                    referencedColumnName: id_tipo_documento
            orphanRemoval: false
        idDeptoFuncional:
            targetEntity: TblDepartamentosFuncionales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_depto_funcional:
                    referencedColumnName: id_depto_funcional
            orphanRemoval: false
        idDireccionSreci:
            targetEntity: TblDireccionesSreci
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_direccion_sreci:
                    referencedColumnName: id_direccion_sreci
            orphanRemoval: false
        idEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idInstitucion:
            targetEntity: TblInstituciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_institucion:
                    referencedColumnName: id_institucion
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idFuncionarioAsignado:
            targetEntity: TblFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_funcionario_asignado:
                    referencedColumnName: id_funcionario
            orphanRemoval: false
        idTipoComunicacion:
            targetEntity: TblTipoComunicacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_comunicacion:
                    referencedColumnName: id_tipo_comunicacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
