BackendBundle\Entity\TblCorrespondenciaEnc:
    type: entity
    table: tbl_correspondencia_enc
    indexes:
        fki_enc_direccion_sreci:
            columns:
                - cod_direccion_sreci
        fki_enc_institucion:
            columns:
                - cod_institucion
        fki_enc_usuario:
            columns:
                - cod_usuario
        fki_enc_estado:
            columns:
                - cod_estado
    id:
        codCorrespondenciaEnc:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            id: true
            column: cod_correspondencia_enc
            generator:
                strategy: SEQUENCE
    fields:
        idCorrespondenciaEnc:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_correspondencia_enc
        descCorrespondenciaEnc:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: desc_correspondencia_enc
        fechaIngreso:
            type: date
            nullable: true
            column: fecha_ingreso
        fechaMaxEntrega:
            type: date
            nullable: true
            column: fecha_max_entrega
    manyToOne:
        codInstitucion:
            targetEntity: TblInstituciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_institucion:
                    referencedColumnName: cod_institucion
            orphanRemoval: false
        codUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_usuario:
                    referencedColumnName: cod_usuario
            orphanRemoval: false
        codEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_estado:
                    referencedColumnName: cod_estado
            orphanRemoval: false
        codDireccionSreci:
            targetEntity: TblDireccionesSreci
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_direccion_sreci:
                    referencedColumnName: cod_direccion_sreci
            orphanRemoval: false
    lifecycleCallbacks: {  }
