BackendBundle\Entity\TblDepartamentosFuncionales:
    type: entity
    table: tbl_departamentos_funcionales
    indexes:
        fki_deptos_direcciones:
            columns:
                - id_direccion_sreci
        tbl_departamentos_funcionales_cod_depto_funcional_idx:
            columns:
                - cod_depto_funcional
    uniqueConstraints:
        tbl_departamentos_funcionales_cod_depto_funcional_key:
            columns:
                - cod_depto_funcional
    id:
        idDeptoFuncional:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_depto_funcional
            generator:
                strategy: SEQUENCE
    fields:
        codDeptoFuncional:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: cod_depto_funcional
        descDeptoFuncional:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: desc_depto_funcional
        inicialesDeptoFuncional:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_depto_funcional
        emailDireccion:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: email_direccion
    manyToOne:
        idDireccionSreci:
            targetEntity: TblDireccionesSreci
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_direccion_sreci:
                    referencedColumnName: id_direccion_sreci
            orphanRemoval: false
    lifecycleCallbacks: {  }
