BackendBundle\Entity\TblDocumentos:
    type: entity
    table: tbl_documentos
    indexes:
        fki_documento_det:
            columns:
                - cod_correspondencia_det
        fki_documento_usuario:
            columns:
                - cod_usuario
    id:
        codDocumento:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            column: cod_documento
            generator:
                strategy: SEQUENCE
    fields:
        idDocumento:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_documento
        descDocumento:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: desc_documento
        urlDocumento:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: url_documento
        fechaIngreso:
            type: date
            nullable: true
            column: fecha_ingreso
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
        miniImagen:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: mini_imagen
        status:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
    manyToOne:
        codCorrespondenciaDet:
            targetEntity: TblCorrespondenciaDet
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_correspondencia_det:
                    referencedColumnName: cod_correspondencia_det
            orphanRemoval: false
        codUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_usuario:
                    referencedColumnName: cod_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
