BackendBundle\Entity\TblDocumentos:
    type: entity
    table: tbl_documentos
    indexes:
        fki_co_det_docum:
            columns:
                - id_correspondencia_det
        fki_doc_user:
            columns:
                - id_usuario
        tbl_documentos_cod_documento_idx:
            columns:
                - cod_documento
        fki_enc_doc:
            columns:
                - id_correspondencia_enc
    uniqueConstraints:
        tbl_documentos_cod_documento_key:
            columns:
                - cod_documento
    id:
        idDocumento:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_documento
            generator:
                strategy: SEQUENCE
    fields:
        codDocumento:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cod_documento
        descDocumento:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: desc_documento
        urlDocumento:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: url_documento
        fechaIngreso:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_ingreso
        fechaModificacion:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_modificacion
        miniImagen:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: mini_imagen
        status:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
    manyToOne:
        idCorrespondenciaDet:
            targetEntity: TblCorrespondenciaDet
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_correspondencia_det:
                    referencedColumnName: id_correspondencia_det
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idCorrespondenciaEnc:
            targetEntity: TblCorrespondenciaEnc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_correspondencia_enc:
                    referencedColumnName: id_correspondencia_enc
            orphanRemoval: false
    lifecycleCallbacks: {  }
