BackendBundle\Entity\TblEstados:
    type: entity
    table: tbl_estados
    indexes:
        tbl_estados_cod_estado_idx:
            columns:
                - cod_estado
    uniqueConstraints:
        tbl_estados_cod_estado_key:
            columns:
                - cod_estado
    id:
        idEstado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_estado
            generator:
                strategy: SEQUENCE
    fields:
        codEstado:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: cod_estado
        descripcionEstado:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: descripcion_estado
        inicalesEstado:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: inicales_estado
        grupoEstado:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: grupo_estado
    lifecycleCallbacks: {  }
