BackendBundle\Entity\TblInstituciones:
    type: entity
    table: tbl_instituciones
    indexes:
        fki_user_institucion:
            columns:
                - id_usuario_creador
        tbl_instituciones_cod_institucion_idx:
            columns:
                - cod_institucion
        fki_pais_inst:
            columns:
                - id_pais
        fki_inst_tipo:
            columns:
                - id_tipo_institucion
    uniqueConstraints:
        tbl_instituciones_cod_institucion_key:
            columns:
                - cod_institucion
    id:
        idInstitucion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_institucion
            generator:
                strategy: SEQUENCE
    fields:
        codInstitucion:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
            column: cod_institucion
        descInstitucion:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
            column: desc_institucion
        perfilInstitucion:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: perfil_institucion
        direccionInstitucion:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: direccion_institucion
        telefonoInstitucion:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: telefono_institucion
        celularInstitucion:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: celular_institucion
        emailInstitucion:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
            column: email_institucion
        fechaIngreso:
            type: date
            nullable: true
            options:
                default: '2999-12-31'
            column: fecha_ingreso
    manyToOne:
        idTipoInstitucion:
            targetEntity: TblTipoInstitucion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_institucion:
                    referencedColumnName: id_tipo_institucion
            orphanRemoval: false
        idPais:
            targetEntity: TblPais
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pais:
                    referencedColumnName: id_pais
            orphanRemoval: false
        idUsuarioCreador:
            targetEntity: TblUsuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario_creador:
                    referencedColumnName: id_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
