BackendBundle\Entity\TblPais:
    type: entity
    table: tbl_pais
    id:
        codPais:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            column: cod_pais
            generator:
                strategy: SEQUENCE
    fields:
        idPais:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_pais
        descPais:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: desc_pais
        inicialesPais:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_pais
        codigoPostal:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: codigo_postal
        codContinente:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: cod_continente
    lifecycleCallbacks: {  }
