BackendBundle\Entity\TblPrioridades:
    type: entity
    table: tbl_prioridades
    indexes:
        tbl_prioridades_cod_prioridad_idx:
            columns:
                - cod_prioridad
    id:
        idPrioridad:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_prioridad
            generator:
                strategy: SEQUENCE
    fields:
        codPrioridad:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: cod_prioridad
        descPrioridad:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: desc_prioridad
        inicialesPrioridad:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_prioridad
    lifecycleCallbacks: {  }
