BackendBundle\Entity\TblSecuenciales:
    type: entity
    table: tbl_secuenciales
    indexes:
        fki_direccion_sec:
            columns:
                - id_direccion_sreci
        idx_cod_secuencia:
            columns:
                - cod_secuencial
        fki_id_depto_funcional_secuencias:
            columns:
                - id_depto_funcional
        fki_secuncia_doc:
            columns:
                - id_tipo_documento
        fki_tipo_user_secuencias:
            columns:
                - id_tipo_usuario
    uniqueConstraints:
        FK_uni_secuencia:
            columns:
                - cod_secuencial
                - id_depto_funcional
                - id_tipo_documento
    id:
        idSecuencial:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_secuencial
            generator:
                strategy: SEQUENCE
    fields:
        codSecuencial:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: cod_secuencial
        valor1:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: valor_1
        valor2:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: valor_2
        tablaSecuencia:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: tabla_secuencia
        reservada:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        actualizada:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        habilitada:
            type: boolean
            nullable: true
            options:
                default: false
        despacho:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
    manyToOne:
        idDireccionSreci:
            targetEntity: TblDireccionesSreci
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_direccion_sreci:
                    referencedColumnName: id_direccion_sreci
            orphanRemoval: false
        idDeptoFuncional:
            targetEntity: TblDepartamentosFuncionales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_depto_funcional:
                    referencedColumnName: id_depto_funcional
            orphanRemoval: false
        idTipoDocumento:
            targetEntity: TblTipoDocumento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_documento:
                    referencedColumnName: id_tipo_documento
            orphanRemoval: false
        idTipoUsuario:
            targetEntity: TblTipoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_usuario:
                    referencedColumnName: id_tipo_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
