BackendBundle\Entity\TblTipoUsuario:
    type: entity
    table: tbl_tipo_usuario
    indexes:
        tbl_tipo_usuario_cod_tipo_usuario_idx:
            columns:
                - cod_tipo_usuario
    uniqueConstraints:
        tbl_tipo_usuario_cod_tipo_usuario_key:
            columns:
                - cod_tipo_usuario
    id:
        idTipoUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_usuario
            generator:
                strategy: SEQUENCE
    fields:
        codTipoUsuario:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: cod_tipo_usuario
        descTipoUsuario:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: desc_tipo_usuario
        inicialesTipoUsuario:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_tipo_usuario
    lifecycleCallbacks: {  }
