BackendBundle\Entity\TblTipoInstitucion:
    type: entity
    table: tbl_tipo_institucion
    indexes:
        tbl_tipo_institucion_cod_tipo_institucion_idx:
            columns:
                - cod_tipo_institucion
    id:
        idTipoInstitucion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_institucion
            generator:
                strategy: SEQUENCE
    fields:
        codTipoInstitucion:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: cod_tipo_institucion
        descTipoInstitucion:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: desc_tipo_institucion
        inicialesTipoInstitucion:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_tipo_institucion
    lifecycleCallbacks: {  }
