BackendBundle\Entity\TblUsuarios:
    type: entity
    table: tbl_usuarios
    indexes:
        fki_tipo_funcionario_user:
            columns:
                - id_tipo_funcionario
        fki_tipo_user:
            columns:
                - id_tipo_usuario
        idx_cod_user:
            columns:
                - cod_usuario
        fki_deptos_user:
            columns:
                - id_depto_funcional
        fki_estados_user:
            columns:
                - id_estado
    id:
        idUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_usuario
            generator:
                strategy: SEQUENCE
    fields:
        codUsuario:
            type: string
            nullable: false
            length: 13
            options:
                fixed: false
            column: cod_usuario
        nombre1Usuario:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: nombre1_usuario
        nombre2Usuario:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: nombre2_usuario
        apellido1Usuario:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: apellido1_usuario
        apellido2Usuario:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: apellido2_usuario
        emailUsuario:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: email_usuario
        inicialesUsuario:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: iniciales_usuario
        passwordUsuario:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: password_usuario
        imagenUsuario:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: imagen_usuario
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
    manyToOne:
        idEstado:
            targetEntity: TblEstados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idTipoFuncionario:
            targetEntity: TblTiposFuncionarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_funcionario:
                    referencedColumnName: id_tipo_funcionario
            orphanRemoval: false
        idDeptoFuncional:
            targetEntity: TblDepartamentosFuncionales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_depto_funcional:
                    referencedColumnName: id_depto_funcional
            orphanRemoval: false
        idTipoUsuario:
            targetEntity: TblTipoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_usuario:
                    referencedColumnName: id_tipo_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
