## YAML Template.
## Author: Nahum Martinez
## Fecha: 22-08-2017
---
# Ruta para Ingresar la Correspondencia de la API
# Nuevo Ingreso de Correspondencia
correspondencia_new:
    path: /new
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:new" }
    methods: POST

# Editar Correspondencia Existente
correspondencia_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:edit", id:null }
    methods: POST
    
correspondencia_upload_image:
    path: /upload-image/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:upload", id:null }
    methods: POST
    
correspondencia_upload_pdf:
    path: /upload-pdf/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:upload", id:null }
    methods: POST