## YAML Template.
## Author: Nahum Martinez
## Fecha: 22-08-2017
---
# Ruta para Ingresar la Correspondencia de la API
# Nuevo Ingreso de Correspondencia
correspondencia_newCorrespondencia:
    path: /new-correspondencia
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:newCorrespondencia" }
    methods: POST
    
# Nuevo Ingreso de Correspondencia por Tipo
correspondencia_newCorrespondenciaTipo:
    path: /new-correspondencia-tipo
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:newCorrespondenciaTipo" }
    methods: POST

# Editar Correspondencia Existente
correspondencia_editCorrespondencia:
    path: /edit-correspondencia/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:editCorrespondencia", id:null }
    methods: POST
    
correspondencia_upload_image:
    path: /upload-image/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:upload", id:null }
    methods: POST
    
correspondencia_upload_pdf:
    path: /upload-pdf/{id}
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:upload", id:null }
    methods: POST
    
correspondencia_index:
    path: /index
    defaults: { _controller: "AppBundle:IngresoCorrespondencia:index" }
    methods: POST