## YAML Template.
## 
---
## Ruta para la Index
default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET
    
# Ruta para los Paises
default_pais:
    path: /pais
    defaults: { _controller: "AppBundle:Default:pais" }
    methods: GET
    
# Ruta para el Login de la API
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST