## YAML Template.
---
# Ruta para Ingresar los Documentos de la API
documento_new:
    path: /new
    defaults: { _controller: "AppBundle:Documentos:new" }
    methods: POST

documento_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Documentos:edit", id:null }
    methods: POST
    
documento_upload_image:
    path: /upload-image/{id}
    defaults: { _controller: "AppBundle:Documentos:upload", id:null }
    methods: POST
    
documento_upload_pdf:
    path: /upload-pdf/{id}
    defaults: { _controller: "AppBundle:Documentos:upload", id:null }
    methods: POST
    
documento_listaDocumentos:
    path: /listar-documentos
    defaults: { _controller: "AppBundle:Documentos:listaDocumentos" }
    methods: POST
    
documento_borrarDocumentoServer:
    path: /borrar-documento-server
    defaults: { _controller: "AppBundle:Documentos:borrarDocumentoServer" }
    methods: POST

documento_subirDocumentosComunicacion:
    path: /subir-documentos-comunicacion
    defaults: { _controller: "AppBundle:Documentos:subirDocumentosComunicacion" }
    methods: POST
    
documento_borrarDocumentosComunicacion:
    path: /borrar-documentos-comunicacion
    defaults: { _controller: "AppBundle:Documentos:borrarDocumentosComunicacion" }
    methods: POST
    