## YAML Template.
---
# Ruta para Ingresar los Documentos de la API
documento_new:
    path: /new
    defaults: { _controller: "AppBundle:Documentos:new" }
    methods: POST

documento_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Documentos:edit", id:null }
    methods: POST
    
documento_upload_image:
    path: /upload-image/{id}
    defaults: { _controller: "AppBundle:Documentos:upload", id:null }
    methods: POST
    
documento_upload_pdf:
    path: /upload-pdf/{id}
    defaults: { _controller: "AppBundle:Documentos:upload", id:null }
    methods: POST