## YAML Template.
## Author: Nahum Martinez
## Fecha: 28-08-2017
---
# Ruta para Seleccionar Listas Comunes
# Lista de Estados de Usuarios
listascomunes_estadosUsuarioList:
    path: /estados-user-list
    defaults: { _controller: "AppBundle:ListasComunes:estadosUsuarioList" }
    methods: POST
    
# Lista de Estados de Comunicaciones | 30-08-2017
listascomunes_estadosComunicacionList:
    path: /estados-comunicacion-list
    defaults: { _controller: "AppBundle:ListasComunes:estadosComunicacionList" }
    methods: POST

# Lista de Tipo de Usuarios
listascomunes_tipoUsuarioList:
    path: /tipo-usuario-list
    defaults: { _controller: "AppBundle:ListasComunes:tipoUsuarioList"}
    methods: POST
    
# Lista de Tipo de Funcionario
listascomunes_tipoFuncionarioList:
    path: /tipo-funcionario-list
    defaults: { _controller: "AppBundle:ListasComunes:tipoFuncionarioList"}
    methods: POST
    
# Lista de Direcciones SRECI
listascomunes_direccionSreciList:
    path: /dir-sreci-list
    defaults: { _controller: "AppBundle:ListasComunes:direccionSreciList"}
    methods: POST
    
# Lista de Sub Direcciones
listascomunes_deptoFuncionalList:
    path: /subdir-sreci-list
    defaults: { _controller: "AppBundle:ListasComunes:deptoFuncionalList"}
    methods: POST
    
# Lista de Sub Direcciones por Usuario Logeado | 2017-09-15
listascomunes_deptoFuncionalUser:
    path: /depto-func-user
    defaults: { _controller: "AppBundle:ListasComunes:deptoFuncionalUser"}
    methods: POST
   
# Lista de Departamento Funcional
listascomunes_deptoFuncionalUserList:
    path: /depto-funcional-user-list
    defaults: { _controller: "AppBundle:ListasComunes:deptoFuncionalUserList"}
    methods: POST
    
# Lista de Instituciones | 30-08-2017
listascomunes_institucionesSreci:
    path: /instituciones-sreci-list
    defaults: { _controller: "AppBundle:ListasComunes:institucionesSreci"}
    methods: POST
    
# Lista de Tipo de Instituciones | 31-08-2017
listascomunes_tipoInstituciones:
    path: /tipo-instituciones-sreci-list
    defaults: { _controller: "AppBundle:ListasComunes:tipoInstituciones"}
    methods: POST
    
# Lista de Paises | 30-08-2017
listascomunes_paisesList:
    path: /paises-list
    defaults: { _controller: "AppBundle:ListasComunes:paisesList"}
    methods: POST
    
# Lista de Tipo de Documento | 01-09-2017
listascomunes_tipoDocumentoList:
    path: /tipo-documento-list
    defaults: { _controller: "AppBundle:ListasComunes:tipoDocumentoList"}
    methods: POST
    
 # Lista de Comunicaciones Ingresadas | 11-09-2017
listascomunes_comIngresadasList:
    path: /com-ingresadas-list
    defaults: { _controller: "AppBundle:ListasComunes:comIngresadasList"}
    methods: POST
 
 # Lista de Comunicaciones Pendientes | 11-09-2017
listascomunes_comPendientesList:
    path: /com-pendientes-list
    defaults: { _controller: "AppBundle:ListasComunes:comPendientesList"}
    methods: POST
    
 # Lista de Comunicaciones Finzalizadas | 11-09-2017
listascomunes_comFinalizadasList:
    path: /com-finalizados-list
    defaults: { _controller: "AppBundle:ListasComunes:comFinalizadasList"}
    methods: POST
    
 # Listado de Oficios a Asignar | 12-09-2017
listascomunes_asignarOficiosList:
    path: /asignar-oficios-list
    defaults: { _controller: "AppBundle:ListasComunes:asignarOficiosList"}
    methods: POST
    
 # Listado de Oficios a Asignar Page | 14-09-2017
listascomunes_asignarOficiosPageList:
    path: /asignar-oficios-page-list
    defaults: { _controller: "AppBundle:ListasComunes:asignarOficiosPageList"}
    methods: GET
    
# Listado de Tipos de Funcionarios | 15-09-2017
listascomunes_tipoFuncionariosList:
    path: /tipo-funcionarios-list
    defaults: { _controller: "AppBundle:ListasComunes:tipoFuncionariosList"}
    methods: POST
    
# Listado de Funcionarios | 15-09-2017
listascomunes_funcionariosList:
    path: /funcionarios-list
    defaults: { _controller: "AppBundle:ListasComunes:funcionariosList"}
    methods: POST

# Listado de Funcionarios po Depto Funcional | 15-09-2017
listascomunes_funcionariosAsignadosList:
    path: /funcionarios-depto-list
    defaults: { _controller: "AppBundle:ListasComunes:funcionariosAsignadosList"}
    methods: POST
    
 ## Listado de Los Oficios Asignados por Usuario (Funcionario) | Modulo Seguimiento
seguimiento_finalizarOficiosList:
    path: /finalizar-oficios-list
    defaults: { _controller: "AppBundle:ListasComunes:finalizarOficiosList" }
    methods: POST
    
 ## Listado de Los Oficios Asignados por Usuario (Funcionario) Detalle | Modulo Seguimiento
seguimiento_finalizarOficiosListDet:
    path: /finalizar-oficios-det-list
    defaults: { _controller: "AppBundle:ListasComunes:finalizarOficiosListDet" }
    methods: POST