## YAML Template.
## 
---

# Ruta para la Solicitud de Cambio de Fechas
default_solicitudCambioFecha:
    path: /solicitud-cambio-fecha
    defaults: { _controller: "AppBundle:MantCambioFechas:solicitudCambioFecha" }
    methods: POST
    
 # Ruta para el Cambio de Fechas
default_cambioFecha:
    path: /cambio-fecha
    defaults: { _controller: "AppBundle:MantCambioFechas:cambioFecha" }
    methods: POST
    
# Ruta para la Consulta de la Comunicacion
default_buscaComunicacion:
    path: /busca-comunicacion
    defaults: { _controller: "AppBundle:MantCambioFechas:buscaComunicacion" }
    methods: POST
    
# Ruta para el Mantenimiento de Instituciones
default_mantenimientoInstitucionNew:
    path: /mantenimiento-institucion-new
    defaults: { _controller: "AppBundle:MantInstituciones:mantenimientoInstitucionNew" }
    methods: POST
    
# Ruta para el Edicion de Instituciones
default_mantenimientoInstitucionEdit:
    path: /mantenimiento-institucion-edit
    defaults: { _controller: "AppBundle:MantInstituciones:mantenimientoInstitucionEdit" }
    methods: POST
    
# Ruta para la Busqueda de Instituciones
default_mantenimientoInstitucionSearch:
    path: /mantenimiento-institucion-busca
    defaults: { _controller: "AppBundle:MantInstituciones:mantenimientoInstitucionSearch" }
    methods: POST