## YAML Template.
---
## Redireccionamiento de las Ruta por Defecto | Modulo Seguimiento
seguimiento_asignarOficio:
    path: /asignar-oficio
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:asignarOficio" }
    methods: POST

## Transformacion de la Fechas TimeStamp | Modulo Seguimiento
seguimiento_convertirFechasTimeStamp:
    path: /convertir-fechas-timestamp
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:convertirFechasTimeStamp" }
    methods: POST
    
## Finalizacion de Comunicacion | Modulo Seguimiento
seguimiento_finalizarOficio:
    path: /finalizar-oficio-asignado
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:finalizarOficio" }
    methods: POST
    
## Creacion de Oficio de Respuesta | Modulo Seguimiento
seguimiento_creacionOficioResp:
    path: /creacion-oficio-asignado
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:creacionOficioResp" }
    methods: POST
    
## Creacion Actividad de Respuesta | Modulo Seguimiento
seguimiento_creacionActividadResp:
    path: /creacion-actividad-resp
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:creacionActividadResp" }
    methods: POST
    
## Listado de la Comunicacion Enc en Busqueda | Modulo Seguimiento
seguimiento_seguimientoEncList:
    path: /seguimiento-search-comunicacion-enc
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:seguimientoEncList" }
    methods: POST
    
## Listado de la Comunicacion Det en Busqueda | Modulo Seguimiento
seguimiento_seguimientoDetList:
    path: /seguimiento-search-comunicacion-det
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:seguimientoDetList" }
    methods: POST