## YAML Template.
---
## Redireccionamiento de las Ruta por Defecto | Modulo Seguimiento
seguimiento_asignarOficio:
    path: /asignar-oficio
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:asignarOficio" }
    methods: POST

## Transformacion de la Fechas TimeStamp | Modulo Seguimiento
seguimiento_convertirFechasTimeStamp:
    path: /convertir-fechas-timestamp
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:convertirFechasTimeStamp" }
    methods: POST
    
## Listado de Los Oficios Asignados por Usuario (Funcionario) | Modulo Seguimiento
seguimiento_finalizarOficio:
    path: /finalizar-oficio-asignado
    defaults: { _controller: "AppBundle:SeguimientoCorrespondencia:finalizarOficio" }
    methods: POST