## YAML Template.
---
## Redireccionamiento de las Ruta por Defecto | Modulo Unidad de Correspondencia
unidadCorrespondencia_entradaCorrespondencia:
    path: /entrada-correspondencia
    defaults: { _controller: "AppBundle:UnidadCorrespondencia:entradaCorrespondencia" }
    methods: POST
unidadCorrespondencia_salidaCorrespondencia:
    path: /salida-correspondencia
    defaults: { _controller: "AppBundle:UnidadCorrespondencia:salidaCorrespondencia" }
    methods: POST
