## YAML Template.
---
# Ruta para los Usuarios de la API
usuario_new:
    path: /new
    defaults: { _controller: "AppBundle:Usuario:new" }
    methods: POST

usuario_edit:
    path: /edit
    defaults: { _controller: "AppBundle:Usuario:edit" }
    methods: POST
    
usuario_upload_image:
    path: /upload-image-user
    defaults: { _controller: "AppBundle:Usuario:uploadImage" }
    methods: POST

usuario_changePassUser:
    path: /change-pass-user
    defaults: { _controller: "AppBundle:Usuario:changePassUser" }
    methods: POST

usuario_detailsUser:
    path: /user-details
    defaults: { _controller: "AppBundle:Usuario:detailsUser" }
    methods: POST
